version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            py -3 -m venv venv
            venv\Scripts\activate
      - run:
          name: Running auth
          command: |
            venv\Scripts\activate
            py -3 auth.py
      - run:
          name: running test
          command: |
            venv\Scripts\activate
            py -3 test.py
      - store_artifacts:
          path: test-reports/
          destination: sprint3
