version: 2
jobs:
  auth:
    docker:
      - image: circleci/python:3.6
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Running auth
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 auth.py
      - store_artifacts:
          path: test-reports/
          destination: sprint3
  test:
    docker:
      - image: circleci/python:3.6
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: mkdir test-reports          
      - run:
          name: running test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 test.py
      - store_artifacts:
          path: test-reports/
          destination: sprint3
workflows:
  version: 2
  build:
    jobs:
      - auth
      - test